#!/bin/bash
echo "🚀 RetinaFace Manual Installation Guide"
echo ""
echo "⚠️  Kailangan mo ng sudo access para sa Python dev headers"
echo ""
echo "Step 1: Install Python Development Headers"
echo "sudo apt-get install python3-dev python3.13-dev build-essential"
echo ""
echo "Step 2: Install MXNet"
echo "pip install --user mxnet"
echo ""
echo "Step 3: Build Cython Extensions"
echo "cd /home/renz/Desktop/eduvision/retinaface"
echo "make"
echo ""
echo "Step 4: Test"
echo "cd /home/renz/Desktop/eduvision/retinaface"
echo "python3 test.py"
echo ""
echo "✅ Model files are already ready at: retinaface/model/R50/"
